import os
import platform
from collections.abc import Callable
from textwrap import dedent
from typing import Optional

from Cython import __version__ as __cythonversion__

from hatch_cython.__about__ import __version__
from hatch_cython.constants import NORM_GLOB, UAST
from hatch_cython.types import P, T


def stale(src: str, dest: str):
    if not os.path.exists(src) or not os.path.exists(dest):
        return True
    return (os.path.getmtime(src) >= os.path.getmtime(dest)) or (os.path.getctime(src) >= os.path.getctime(dest))


def memo(func: Callable[P, T]) -> Callable[P, T]:
    global_cache: dict = {}

    def wrapped(*args: P.args, **kwargs: P.kwargs) -> T:
        # if we have a class, store the cache on the instance itself so that
        # the cache lifetime is tied to the instance.  Keying by id() alone
        # is unsafe because Python reuses memory addresses after GC, causing
        # a new instance to get a stale cache hit from a previous one.
        # note: access obj.__dict__ directly rather than hasattr/getattr to
        # avoid infinite recursion when a property is decorated with @memo.
        if len(args) != 0 and func.__name__ in dir(args[0]):
            obj = args[0]
            try:
                cache = obj.__dict__.setdefault("__memo__", {})
            except AttributeError:
                cache = global_cache.setdefault(id(obj), {})
            if func.__name__ not in cache:
                cache[func.__name__] = func(*args, **kwargs)
            return cache[func.__name__]

        if None not in global_cache:
            global_cache[None] = func(*args, **kwargs)
        return global_cache[None]

    return wrapped


@memo
def plat():
    return platform.system().lower()


@memo
def aarch():
    return platform.machine().lower()


def options_kws(kwds: dict):
    return ",\n\t".join((f"{k}={v!r}" for k, v in kwds.items()))


def parse_user_glob(
    uglob: str,
    variant: Optional[str] = None,
    modifier: Optional[Callable[[str], str]] = None,
):
    if variant is None:
        variant = NORM_GLOB
    pre = uglob.replace("\\*", UAST)
    if modifier:
        pre = modifier(pre)
    imd = pre.replace("*", variant)
    return fr'{imd.replace(UAST, "*")}'


def autogenerated(keywords: dict):
    return dedent(f"""# DO NOT EDIT.
# Autoformatted by hatch-cython.
# Version: {__version__}
# Cython: {__cythonversion__}
# Platform: {plat()}
# Architecture: {aarch()}
# Keywords: {keywords!r}
""")
